django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('app/', include('home.urls')),
    path('', include('shop.urls')),
    path('user_account/', include('user_account.urls')),
    path('calendar/', include('event_calendar.urls')),
    path('order/', include('checkout.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_app/event_calendar/urls.py
from django.urls import path, include
from event_calendar import views

urlpatterns = [
    path('', views.calendar, name='calendar'),
    path('new_event/', views.new_event, name='new_event')
    # path('sp/', views.home_sp, name='casa'),
]

django_app/event_calendar/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.


class CalendarEvent(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField(blank=True)
    date_created = models.DateField(default=datetime.now)
    event_start_date = models.DateTimeField(default=datetime.now)
    event_end_date = models.DateTimeField(default=datetime.now)
    colors = [
        ('bg-primary', 'Primary'),
        ('bg-secondary', 'Secondary'),
        ('bg-success', 'Success'),
        ('bg-info', 'Info'),
        ('bg-warning', 'Warning'),
        ('bg-danger', 'Danger'),
        ('bg-light', 'Light'),
        ('bg-dark', 'Dark'),
        ('bg-white', 'White'),
        ('bg-transparent', 'Transparent'),
        ('bg-gradient-primary', 'Gradient Primary'),
        ('bg-gradient-secondary', 'Gradient Secondary'),
        ('bg-gradient-success', 'Gradient Success'),
        ('bg-gradient-info', 'Gradient Info'),
        ('bg-gradient-warning', 'Gradient Warning'),
        ('bg-gradient-danger', 'Gradient Danger'),
        ('bg-gradient-light', 'Gradient Light'),
        ('bg-gradient-dark', 'Gradient Dark'),
        ('bg-gradient-faded-primary', 'Faded Gradient Primary'),
        ('bg-gradient-faded-secondary', 'Faded Gradient Secondary'),
        ('bg-gradient-faded-success', 'Faded Gradient Success'),
        ('bg-gradient-faded-info', 'Faded Gradient Info'),
        ('bg-gradient-faded-warning', 'Faded Gradient Warning'),
        ('bg-gradient-faded-danger', 'Faded Gradient Danger'),
        ('bg-gradient-faded-light', 'Faded Gradient Light'),
        ('bg-gradient-faded-dark', 'Faded Gradient Dark'),
        ('bg-gradient-faded-white', 'Faded Gradient White'),
        ('bg-gradient-faded-primary-vertical', 'Faded Primary Vertical'),
        ('bg-gradient-faded-secondary-vertical', 'Faded Secondary Vertical'),
        ('bg-gradient-faded-success-vertical', 'Faded Success Vertical'),
        ('bg-gradient-faded-info-vertical', 'Faded Info Vertical'),
        ('bg-gradient-faded-warning-vertical', 'Faded Warning Vertical'),
        ('bg-gradient-faded-danger-vertical', 'Faded Danger Vertical'),
        ('bg-gradient-faded-light-vertical', 'Faded Light Vertical'),
        ('bg-gradient-faded-dark-vertical', 'Faded Dark Vertical'),
        ('bg-gradient-faded-white-vertical', 'Faded White Vertical'),
    ]
    color = models.CharField(max_length=40, choices=colors, default='bg-primary')
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.title} by {self.author.username} on {self.date_created}'

django_app/event_calendar/forms.py
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField
from django import forms
from .models import CalendarEvent

class CalendarEventBodyForm(forms.ModelForm):
    foo = forms.CharField(widget=SummernoteWidget())
    content = forms.CharField(widget=SummernoteInplaceWidget())

    class Meta:
        model = CalendarEvent
        fields = ('body',)
        widgets = {
            'foo': SummernoteWidget(),
            'bar': SummernoteInplaceWidget(),
        }


class CalendarEventForm(forms.ModelForm):
    class Meta:
        model = CalendarEvent
        fields = ['title', 'event_start_date', 'event_end_date', 'color', 'approved']
        widgets = {
            'event_start_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'event_end_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }

    def __init__(self, *args, **kwargs):
        super(CalendarEventForm, self).__init__(*args, **kwargs)
        self.fields['event_start_date'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['event_end_date'].input_formats = ('%Y-%m-%dT%H:%M',)

django_app/event_calendar/views.py
from django.shortcuts import render, redirect
from .models import CalendarEvent
from .forms import CalendarEventForm, CalendarEventBodyForm
from django.contrib.auth.models import User
from datetime import date
from datetime import datetime
import pytz


def calendar(request):
    user_agent = request.META['HTTP_USER_AGENT']

    all_events = CalendarEvent.objects.all().order_by('-event_start_date')

    # Define the Central Time Zone
    central_timezone = pytz.timezone('America/Chicago')

    # Get the current date in Central Time Zone (as a date object)
    today = datetime.now(central_timezone).date()

    todays_events = []
    upcoming_events = []
    past_events = []

    for event in all_events:
        if event.event_start_date.date() == today:
            todays_events.append(event)
        elif event.event_start_date.date() > today:
            upcoming_events.append(event)
        else:
            past_events.append(event)

    # Concatenate the lists in the desired order
    events = todays_events + upcoming_events + past_events

    context = {
        'events': events,
        'today': today,
    }
    if 'Mobile' in user_agent:
        return render(request, 'event_calendar/calendar.html', context)
    else:
        return render(request, 'event_calendar/calendar.html', context)


def new_event(request):
    user_agent = request.META['HTTP_USER_AGENT']
    event_model = CalendarEvent()
    user = request.user
    forms = CalendarEventForm(request.POST)
    body_form = CalendarEventBodyForm(request.POST)
    dm_body_3 = request.POST.get('foo')
    if request.method == 'POST':
        if forms.is_valid():
            # Assuming both forms need to be saved to a single CalendarEvent instance
            body = dm_body_3
            event_model.body = body
            event_model.title = forms.cleaned_data["title"]
            event_model.color = forms.cleaned_data["color"]
            event_model.event_start_date = forms.cleaned_data["event_start_date"]
            event_model.event_end_date = forms.cleaned_data["event_end_date"]
            event_model.author = user
            event_model.save()
            # Redirect to a new URL after saving the event
            return redirect('calendar')

    else:
        forms = CalendarEventForm()
        body_form = CalendarEventBodyForm()

    context = {
        'event_forms': forms,
        'bodyform': body_form,
    }
    if 'Mobile' in user_agent:
        return render(request, 'event_calendar/new_event.html', context=context)
    else:
        return render(request, 'event_calendar/new_event.html', context=context)

django_app/event_calendar/templates/event_calendar/calendar.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Calendar {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
    <style>
    .nav-link {
        color: lightgrey;
    }
    .nav {
    --bs-nav-link-padding-x: 1rem;
    --bs-nav-link-padding-y: 0.5rem;
    --bs-nav-link-font-weight: ;
    --bs-nav-link-color: var(--bs-link-color);
    --bs-nav-link-hover-color: #efff42;
    --bs-nav-link-disabled-color: #6c757d;
    display: flex;
    flex-wrap: wrap;
    padding-left: 0;
    margin-bottom: 0;
    list-style: none;
}
    </style>

{% endblock stylesheets %}

{% block content %}
<center><h1> Event Calendar</h1></center>
    <div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="eventModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document" style="display: block; /* Use block display */
    margin-right: 25%;
    margin-top: 10%;
    margin-left: auto;">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #344767">
        <h5 class="modal-title" id="eventModalLabel">Event Details</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="eventModalBody" style="color: black; background-color: lightgrey">
        <!-- Event details will go here -->
      </div>
    </div>
  </div>
</div>
    <div class="container">

    <ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="calendar-tab" data-bs-toggle="tab" data-bs-target="#calendar" type="button" role="tab" aria-controls="calendar" aria-selected="true">Calendar</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="table-tab" data-bs-toggle="tab" data-bs-target="#table" type="button" role="tab" aria-controls="table" aria-selected="false">Table</button>
  </li>

<li class="nav-item ms-auto" role="presentation"> <!-- ms-auto will push it to the right -->
        <a href="{% url 'new_event' %}"><button class="nav-link" id="create-event-tab" type="button">Create Event</button></a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="calendar" role="tabpanel" aria-labelledby="calendar-tab">
      <div class="card card-calendar" style="height: 75vh">
                    <div class="card-body p-3">
                        <div class="calendar" data-bs-toggle="calendar" id="calendar" ></div>
                    </div>
                </div>
    </div>
  </div>
  <div class="tab-pane fade" id="table" role="tabpanel" aria-labelledby="table-tab">
      <br>
      <div class="card">
  <div class="table-responsive">
    <table class="table align-items-center mb-0">
      <thead>
        <tr>
          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Author</th>
          <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Event</th>
          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Status</th>
          <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date/Time</th>
          <th class="text-secondary opacity-7"></th>
        </tr>
      </thead>
      <tbody>
      {% for event in events %}
        <tr>
          <td>
            <div class="d-flex px-2 py-1">
              <div>
                <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpurepng.com%2Fpublic%2Fuploads%2Flarge%2Fpurepng.com-user-iconsymbolsiconsapple-iosiosios-8-iconsios-8-721522596134a4bio.png&f=1&nofb=1&ipt=4cec38da50a382562b765e8aad7e506d7907887188db6e816bbe4c5afe3c8140&ipo=images" class="avatar avatar-sm me-3">
              </div>
              <div class="d-flex flex-column justify-content-center">
                <h6 class="mb-0 text-xs">{{ event.author }}</h6>
                <p class="text-xs text-secondary mb-0">{{ event.author.email }}</p>
              </div>
            </div>
          </td>
          <td>
            <p class="text-xs font-weight-bold mb-0">{{ event.title }}</p>
          </td>
          <td class="align-middle text-center text-sm">
              {% if event.event_start_date.date < today %}
                    <span class="badge badge-sm bg-gradient-light" style="color: black">Passed</span>
                {% elif event.event_start_date.date == today %}
                    <span class="badge badge-sm {{ event.color }}">Today's Event</span>
                {% else %}
                    <span class="badge badge-sm {{ event.color }}">Up & Coming</span>
                {% endif %}
          </td>
          <td class="align-middle text-center">
            <span class="text-secondary text-xs font-weight-bold">{{ event.event_start_date }}</span>
          </td>
          <td class="align-middle">
        <div id="eventBody{{ event.id }}" style="display: none;">
            {{ event.body|safe }}
        </div>
        <a href="javascript:;" class="text-secondary font-weight-bold text-xs" onclick="showEventModal('{{ event.id }}')" data-title="{{ event.title|escapejs }}" data-toggle="tooltip" data-original-title="Edit user">
          View
        </a>
    </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  </div>
{#  <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>#}
</div>
{% endblock content %}

{% block javascripts %}
<script>
        var calendar = new FullCalendar.Calendar(document.getElementById("calendar"), {
            contentHeight: '65vh',
            initialView: "dayGridMonth",
            headerToolbar: {
                start: 'title', // will normally be on the left. if RTL, will be on the right
                center: '',
                end: 'today prev,next' // will normally be on the right. if RTL, will be on the left
            },
            selectable: true,
            editable: true,
            initialDate: '2023-12-01',

            events: [
                {% for event in events %}
                {
                title: '{{ event.title |escapejs }}',
                start: '{{ event.event_start_date|date:"Y-m-d" }}',
                end: '{{ event.event_end_date|date:"Y-m-d" }}',
                className: '{{ event.color }}',
                body: '{{ event.body|escapejs }}'
            },
                {% endfor %}

            ],
            views: {
                month: {
                    titleFormat: {
                        month: "long",
                        year: "numeric"
                    }
                },
                agendaWeek: {
                    titleFormat: {
                        month: "long",
                        year: "numeric",
                        day: "numeric"
                    }
                },
                agendaDay: {
                    titleFormat: {
                        month: "short",
                        year: "numeric",
                        day: "numeric"
                    }
                }
            },

            eventClick: function(info) {
            // Set the title and body of the event in the modal
            document.getElementById('eventModalLabel').textContent = info.event.title;
            document.getElementById('eventModalBody').innerHTML = info.event.extendedProps.body;

            // Show the modal
            var eventModal = new bootstrap.Modal(document.getElementById('eventModal'));
            eventModal.show();

            // Prevent browser default action
            info.jsEvent.preventDefault();
        },
        });

        calendar.render();

    </script>
    <script>
        function showEventModal(eventId) {
            var eventTitle = document.querySelector(`[onclick="showEventModal('${eventId}')"]`).getAttribute('data-title');
            var eventBody = document.getElementById(`eventBody${eventId}`).innerHTML;

            // Update the modal title and body content
            document.getElementById('eventModalLabel').innerText = eventTitle;
            document.getElementById('eventModalBody').innerHTML = eventBody;

            // Show the modal
            var eventModal = new bootstrap.Modal(document.getElementById('eventModal'));
            eventModal.show();
        }
    </script>
{% endblock javascripts %}

django_app/event_calendar/templates/event_calendar/new_event.html
{% extends 'base.html' %}
{% load static %}
{#{% load crispy_forms_tags %}#}

{% block title %} New Event {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}

{% endblock stylesheets %}

{% block content %}
    <div class="container">
<form role="form" action="{% url 'new_event' %}" method="post">
        {% csrf_token %}
            <div class="row justify-content-center">
                <center><h1>Submit an Event</h1></center>
            </div>
<div class="container">
            <div class="form-group row">

        {{ event_forms.title  }}
        {% if event_forms.title.errors %}
            <div class="alert alert-danger">
                {{ event_forms.title.errors }}
            </div>
        {% endif %}


    </div>
</div>
<div class="row">
    <div class="col">
    <div class="form-group">
        <label for="id_event_start_date">Start Date:</label>
        {{ event_forms.event_start_date }}
        {% if event_forms.event_start_date.errors %}
            <div class="alert alert-danger">
                {{ event_forms.event_start_date.errors }}
            </div>
        {% endif %}
    </div>
    </div>
    <!-- Render 'event_end_date' field -->
<div class="col">
    <div class="form-group">
        <label for="id_event_end_date">End Date:</label>
        {{ event_forms.event_end_date  }}
        {% if event_forms.event_end_date.errors %}
            <div class="alert alert-danger">
                {{ event_forms.event_end_date.errors }}
            </div>
        {% endif %}
    </div>
</div>
    <!-- Render 'color' field -->
<div class="col">
    <div class="form-group">
        <label for="id_color">Color:</label>
        {{ event_forms.color }}
        {% if event_forms.color.errors %}
            <div class="alert alert-danger">
                {{ event_forms.color.errors }}
            </div>
        {% endif %}
    </div>
</div>
</div>
            {{ bodyform.foo | safe }}
            {{ bodyform.content }}

            <row class="row justify-content-center">
                <div class="col-4"></div>
                <div class="col-4">
                    <hr>
                    <center>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </center>
                    <br>
                </div>
                <div class="col-4"></div>
            </row>
        </form>
    </div>
{% endblock content %}


{% block javascripts %}

    <script>
    $('#id_foo').on('submit', function() {
        var content = $('#id_content_summernote').summernote('code');
        $('#id_content').val(content);
    });
    </script>

{% endblock javascripts %}